name: e_learning_dashboard
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  intl: ^0.17.0
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/

  #fonts: dm sans 700, cocoa 400, 700, poppins: 300, 400, 500, 600,
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/light.ttf
          weight: 300
        - asset: assets/fonts/poppins/regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/semibold.ttf
          weight: 600
    - family: DmSans
      fonts:
        - asset: assets/fonts/dm_sans/bold.ttf
          weight: 700
    - family: CocoaSharp
      fonts:
        - asset: assets/fonts/dm_sans/bold.ttf
          weight: 700
        - asset: assets/fonts/dm_sans/regular.ttf
          weight: 400